=== Shailla/jeukitue.moteur/sources/map2017.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jkt="http://jkt/map2017.xsd" targetNamespace="http://jkt/map2017.xsd" elementFormDefault="qualified">

	<xs:include schemaLocation="map2017-basicTypes.xsd" />

	<xs:element name="Map">
		<xs:annotation>
			<xs:documentation>Map de jeu</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Plugins" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>Plugins de la Map</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Load" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="Nom" type="xs:string">
										<xs:annotation>
											<xs:documentation>Nom du plugin</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="ParticulesEngines" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>Moteur de particules présents dans la Map</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Neige" type="jkt:TParticulesEngineNeige" />
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="Materiaux" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>Liste des materiaux utilisés (simples couleurs, textures, textures multiples)</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="MateriauSimple" type="jkt:TMateriauSimple" />
							<xs:element name="MateriauTexture" type="jkt:TMateriauTexture" />
							<xs:element name="MateriauMulti" type="jkt:TMateriauTexture" />
						</xs:choice>
						<xs:attribute name="Ref" type="xs:integer" />
					</xs:complexType>
				</xs:element>
				<xs:element name="Lights" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="LightOmni" type="jkt:TLightOmni" />
							<xs:element name="LightTarget" type="jkt:TLightTarget" />
						</xs:choice>
						<xs:attribute name="Ref" type="xs:integer" />
					</xs:complexType>
				</xs:element>
				<xs:element name="Geos" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="GeoSimple" type="jkt:TGeoSimple" />
							<xs:element name="GeoTexture" type="jkt:TGeoTexture" />
							<xs:element name="GeoSimpleMaterial" type="jkt:TGeoSimpleMaterial" />
							<xs:element name="GeoMulti" type="jkt:TGeoMulti" />
						</xs:choice>
						<xs:attribute name="Ref" type="xs:integer" />
					</xs:complexType>
				</xs:element>
				<xs:element name="Imports" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>Autres fichiers Map à importer</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Import" type="jkt:TImport" />
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="EntryPoints" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>Points d'entrée des joueurs dans la Map</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="EntryPoint" type="jkt:TEntryPoint" />
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="TParticulesEngineNeige">
		<xs:sequence>
			<xs:element name="Position" type="jkt:TPosition" />
			<xs:element name="Dimension" type="jkt:TDimension" />
		</xs:sequence>
		<xs:attribute name="Nom" type="xs:string">
			<xs:annotation>
				<xs:documentation>Nom du moteur de particules</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="NbrParticules" type="xs:string">
			<xs:annotation>
				<xs:documentation>Nombre de particles que le moteur de particules doit générer</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="TMateriauSimple">
		<xs:sequence>
			<xs:element name="Ambiante" type="jkt:TColor" />
			<xs:element name="Diffuse" type="jkt:TColor" />
			<xs:element name="Specular" type="jkt:TColor" />
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
	</xs:complexType>

	<xs:complexType name="TMateriauTexture">
		<xs:sequence>
			<xs:element name="Ambiante" type="jkt:TColor" />
			<xs:element name="Diffuse" type="jkt:TColor" />
			<xs:element name="Specular" type="jkt:TColor" />
			<xs:element name="Fichier">
				<xs:complexType>
					<xs:attribute name="Nom" type="xs:string">
						<xs:annotation>
							<xs:documentation>Nom du fichier de texture</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
	</xs:complexType>

	<xs:complexType name="TMateriauMulti">
		<xs:sequence>
			<xs:element name="Ambiante" type="jkt:TColor" />
			<xs:element name="Diffuse" type="jkt:TColor" />
			<xs:element name="Specular" type="jkt:TColor" />
			<xs:element name="Fichier">
				<xs:complexType>
					<xs:attribute name="Nom" type="xs:string">
						<xs:annotation>
							<xs:documentation>Nom du fichier de texture</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="SousMateriaux">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="MateriauSimple" type="jkt:TMateriauSimple" />
						<xs:element name="MateriauTexture" type="jkt:TMateriauTexture" />
						<xs:element name="MateriauMulti" type="jkt:TMateriauTexture" />
					</xs:choice>
					<xs:attribute name="Nbr" type="xs:integer"></xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
	</xs:complexType>

	<xs:complexType name="TLightOmni">
		<xs:sequence>
			<xs:element name="Ambiante" type="jkt:TColor" />
			<xs:element name="Diffuse" type="jkt:TColor" />
			<xs:element name="Specular" type="jkt:TColor" />
			<xs:element name="Position" type="jkt:TPosition" />
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
	</xs:complexType>

	<xs:complexType name="TLightTarget">
		<xs:sequence>
			<xs:element name="Ambiante" type="jkt:TColor" />
			<xs:element name="Diffuse" type="jkt:TColor" />
			<xs:element name="Specular" type="jkt:TColor" />
			<xs:element name="Position" type="jkt:TPosition" />
			<xs:element name="Direction" type="jkt:TPosition" />
			<xs:element name="FallOff">
				<xs:complexType>
					<xs:attribute name="Valeur" type="xs:integer" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
	</xs:complexType>

	<xs:complexType name="TGeoSimple">
		<xs:sequence>
			<xs:element name="Solide">
				<xs:complexType>
					<xs:attribute name="Valeur" type="xs:boolean" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Couleur" type="jkt:TColor" />
			<xs:element name="Sommets">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TPosition" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Faces">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Sommet" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="S1" type="xs:integer" />
								<xs:attribute name="S2" type="xs:integer" />
								<xs:attribute name="S3" type="xs:integer" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
		<xs:attribute name="Nom" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="TGeoSimpleMaterial">
		<xs:sequence>
			<xs:element name="Solide">
				<xs:complexType>
					<xs:attribute name="Valeur" type="xs:boolean" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Materiau">
				<xs:complexType>
					<xs:attribute name="Ref" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Sommets">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TPosition" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="VecteursNormaux">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TPosition" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
		<xs:attribute name="Nom" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="TGeoTexture">
		<xs:sequence>
			<xs:element name="Solide">
				<xs:complexType>
					<xs:attribute name="Valeur" type="xs:boolean" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Materiau">
				<xs:complexType>
					<xs:attribute name="Ref" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Sommets">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TPosition" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="VecteursNormaux">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TPosition" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="SommetsDeTexture">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TTexCoord" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
		<xs:attribute name="Nom" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="TGeoMulti">
		<xs:sequence>
			<xs:element name="Solide">
				<xs:complexType>
					<xs:attribute name="Valeur" type="xs:boolean" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Materiau">
				<xs:complexType>
					<xs:attribute name="Ref" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Sommets">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TPosition" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="VecteursNormaux">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TPosition" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="SommetsDeTexture">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="S" type="jkt:TTexCoord" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="Nbr" type="xs:integer" />
				</xs:complexType>
			</xs:element>
			<xs:element name="SousMateriaux">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="SousMateriau" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="Id" type="xs:integer" />
								<xs:attribute name="NbrFaces" type="xs:integer" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="NbrFaces" type="xs:integer" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Ref" type="xs:integer" />
		<xs:attribute name="Nom" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="TImport">
		<xs:sequence>
			<xs:element name="Translate" type="jkt:TTranslate" minOccurs="0" maxOccurs="1" />
			<xs:element name="Scale" type="jkt:TScale" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="Mode">
			<xs:annotation>
				<xs:documentation>Type d'import à effectuer (add=ajout en sous-Map, merge=fusion de la Map)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="add" />
					<xs:enumeration value="merge" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Nom" type="xs:string">
			<xs:annotation>
				<xs:documentation>Nom de la Map à importer</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="TEntryPoint">
		<xs:sequence>
			<xs:element name="Position" type="jkt:TPosition" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Shailla/jeukitue.moteur/deploy/Map/SceneGrande.map/SceneGrande.map.xml
<?xml version="1.0" encoding="UTF-8"?>
<Map xmlns="http://jkt/map2017.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jkt/map2017.xsd H:/jkt/git/moteur/sources/map2017.xsd">
	<Plugins>
	</Plugins>
	
	<ParticulesEngines>
	</ParticulesEngines>
	
    <Materiaux>
    </Materiaux>
	
    <Lights/>
    
	<Geos>
    </Geos>
	
	<Imports>
		<Import Mode="add" Nom="Scene">
			<Translate X="0.0" Y="0.0" Z="0.0"/>
			<Scale X="5.0" Y="2.0" Z="2.0"/>
		</Import>
	</Imports>
	
    <EntryPoints>
    </EntryPoints>
</Map>

=== Shailla/jeukitue.moteur/deploy/Map/Sol.map/Sol.map.xml
<?xml version="1.0" encoding="UTF-8"?>
<Map xmlns="http://jkt/map2017.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jkt/map2017.xsd H:/jkt/git/moteur/sources/map2017.xsd">
    <Materiaux>
        <MateriauTexture Ref="id-1000">
            <Ambiante R="0.588" G="0.588" B="0.588"/>
            <Diffuse R="0.588" G="0.588" B="0.588"/>
            <Specular R="0.9" G="0.9" B="0.9"/>
            <Fichier Nom="$\Sand3.jpg"/>
        </MateriauTexture>
    </Materiaux>
    <Lights/>
    <Geos>
        <GeoTexture Ref="id-N65571" Nom="Plane01">
<Solide Valeur="true"/>
<Materiau Ref="id-1000"/>
<Sommets Nbr="6">
                <S X="5" Y="-1" Z="5"/>
                <S X="5" Y="-1" Z="-5"/>
                <S X="-5" Y="-1" Z="5"/>
                <S X="-5" Y="-1" Z="-5"/>
                <S X="-5" Y="-1" Z="5"/>
                <S X="5" Y="-1" Z="-5"/>
            </Sommets>
<VecteursNormaux Nbr="6">
                <S X="-0" Y="0" Z="1"/>
                <S X="-0" Y="0" Z="1"/>
                <S X="-0" Y="0" Z="1"/>
                <S X="-0" Y="0" Z="1"/>
                <S X="-0" Y="0" Z="1"/>
                <S X="-0" Y="0" Z="1"/>
            </VecteursNormaux>
<SommetsDeTexture Nbr="6">
                <S U="17.991" V="0.0085"/>
                <S U="0.009" V="0.0085"/>
                <S U="17.991" V="16.9915"/>
                <S U="0.009" V="16.9915"/>
                <S U="17.991" V="16.9915"/>
                <S U="0.009" V="0.0085"/>
            </SommetsDeTexture>
</GeoTexture>
    </Geos>
</Map>
